version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - ./prisma:/app/prisma 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
